apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: traefik
namePrefix: traefik-
namespace: homepage
resources:
  - "./deployment.yml"
  - "./service.yml"
  - "./ingressRoute"


