apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-acme
  namespace: ingress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi