---
# Source: traefik/templates/rbac/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik
  namespace: ingress
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik